services:
  postgres:
    image: postgres
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    env_file:
      - .env
    volumes:
      - nest-postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '${REDIS_PORT:-6379}:6379'
    env_file:
      - .env
    volumes:
      - nest-redis:/data

volumes:
  nest-postgres:
  nest-redis:
