POST http://localhost:3000/tutorials
Content-Type: application/json

{
  "title": "Hello World"
}

###

PATCH http://localhost:3000/tutorials/0e2ad9cd-495b-44bd-a14e-a966108d4b73
Content-Type: application/json

{
  "title": "Updated Tutorial"
}
